/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontendClasses;

import BackendClasses.TrainerRole;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Reem
 */
public class CancelReg extends javax.swing.JFrame {

    /**
     * Creates new form CancelReg
     */
    public CancelReg(TrainerRole trainer) {
        this.trainer = trainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        memberIDField = new javax.swing.JTextField();
        ClassIDField = new javax.swing.JTextField();
        CancelRegButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancel Registration");
        setBackground(new java.awt.Color(204, 204, 204));

        label1.setBackground(new java.awt.Color(153, 255, 153));
        label1.setText("Member ID");

        label2.setBackground(new java.awt.Color(153, 255, 153));
        label2.setText("Class ID");

        memberIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDFieldActionPerformed(evt);
            }
        });

        ClassIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassIDFieldActionPerformed(evt);
            }
        });

        CancelRegButton.setBackground(new java.awt.Color(0, 0, 0));
        CancelRegButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelRegButton.setText("Cancel Registration");
        CancelRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRegButtonActionPerformed(evt);
            }
        });

        backButton1.setBackground(new java.awt.Color(0, 0, 0));
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(ClassIDField))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(CancelRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(backButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(ClassIDField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memberIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIDFieldActionPerformed

    private void ClassIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassIDFieldActionPerformed

    private void CancelRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRegButtonActionPerformed
        if (memberIDField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "please fill out Member ID");
        } else if (ClassIDField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "please fill out class ID");
        } else {
            trainer.cancelRegistration(memberIDField.getText(), ClassIDField.getText());
            this.dispose();
}
    }//GEN-LAST:event_CancelRegButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelRegButton;
    private javax.swing.JTextField ClassIDField;
    private javax.swing.JButton backButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField memberIDField;
    // End of variables declaration//GEN-END:variables
    private TrainerRole trainer;
}
